### ISSUE TITLE
Archives should have hermetic output

### ISSUE THREAD

**Issue by natebosch** [dart-lang/rules_dart#141]
@davidmorgan suggested using `--mtime=@0 --owner=0 --group=0`.

**Comment by davidmorgan** [comment]
It may also be necessary to sort the file list:

tar --mtime=@0 --owner=0 --group=0 -chf temp_tar.tar $(find . -type f | sort)

**Comment by natebosch** [comment]
I think we want the tar option `--sort=name` if it exists all the places we need it to rather than sorting separately.

We'll also want to make sure we are setting the environment variable `LC_ALL` if bazel doesn't do that for us.

**Comment by natebosch** [comment]
See also:
https://reproducible-builds.org/docs/archives/

**Comment by grouma** [comment]
@davidmorgan stated in an internal thread that sorting is not necessary. If we find out that it does unfortunately we can't use `--sort` given that it isn't available in all of our build environments.
