### ISSUE TITLE
Add a dart_development_server rule that...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/rules_dart#15]
- [x] Implicit filegroup of `glob(["web/**"])` + dependencies
- [x] Use `shelf_static` to serve `runfiles` for the binary
- [x] Stretch: Bazel query + watcher to re-run bazel build
- [x] Stretch: Block until bazel build finishes

**Comment by jakemac53** [comment]
https://github.com/dart-lang/rules_dart/pull/22

**Comment by jakemac53** [comment]
https://github.com/dart-lang/rules_dart/pull/33 adds some basic watcher/rebuild functionality, but it doesn't use blaze query or any of that. It simply adds a --watch argument (paths to watch), and --build-target which is the target to build. It also adds blocking on builds etc.

**Comment by jakemac53** [comment]
For the first bullet point `Implicit filegroup of glob(["web/**"]) + dependencies`, I don't know if this is actually something we should do. Today you simply add a `data` dependency on the `dart_ddc_bundle` rule, and that bundle rule is what should contain all your web sources etc.

**Comment by matanlurey** [comment]
I think this is closable :)
