### ISSUE TITLE
[Long term]: Consolidate into less (public) .bzl files and rules

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/rules_dart#39]
No action item for now, but we need to start simplifying what user-visible pieces we have in the near future - this is also an issue internally. For example, `dart_ddc_bundle` - maybe that should just be part of a dart_web_application() macro.

Very careless strawman:
- `dart_library`
- `dart_web_application` ... becomes a macro
  - Creates a dart_library for you from srcs/deps
  - Creates a `dart_ddc_bundle` for you
  - Creates a `dart_web_binary` for you
    - Runs dart2js of script_file.dart to script_file.js and script_file.debug.js (?)
    - We will still need flags for configuring dart2js output
  - Creates one or more `dart_dev_server` rules for you
- `dart_vm_binary` (Doesn't change much/at all)

**Comment by jakemac53** [comment]
Agreed that seems reasonable and would reduce confusion

**Comment by cbracken** [comment]
Moving all the DDC stuff into `web.bzl` seems like a good start. 

Keeping platform-specific rules separate has a few significant advantages. Among other issues, implicit dependencies (e.g., on `protoc` in `dart_proto_library`) drag in the full transitive closure of the tools they depend on, which is annoying for exoblaze users.

Personally, `core.bzl`, `web.bzl`, `vm.bzl` seem good enough as the full set of developer-facing Skylark files.

**Comment by jakemac53** [comment]
Personally I would like to keep the implementations of the actions at least in a separate bzl file, huge python files are not fun to work with imo. The downside being the implementations actually end up being public functions instead of faux-private ones, but maybe we create a `src` folder or something to further separate the private implementations from the public facing rules?

**Comment by cbracken** [comment]
Im fine with that; it's basically what we did with `internal.bzl`
