### ISSUE TITLE
Stop using a bleeding edge SDK build

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/rules_dart#42]
Need a release of the SDK (dev or otherwise) that has https://github.com/dart-lang/sdk/commit/a032a4c952b5dd9e2c14034b2a1d75d11413f545

**Comment by natebosch** [comment]
This would be a lot easier to test if you pushed a branch the official repo instead of using a fork...

**Comment by kevmoo** [comment]
@natebosch would you like me to push to the repo? 😄

**Comment by natebosch** [comment]
LGTM. Confirmed DDC + source maps are working on the codelab repo
