### ISSUE TITLE
PPW: no package dirs?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/rules_dart#44]
Soo close to getting Pop, Pop, Win! working!

See this branch

https://github.com/dart-lang/sample-pop_pop_win/tree/kevmoo_bazel

Ran `bazel run :game_web_ddc_serve`

Had to go digging for the right URL to hit (see https://github.com/dart-lang/bazel/issues/28) 
Figured out it was http://localhost:8080/web/game_web_ddc_bundle.html

<img width="946" alt="screen shot 2016-10-19 at 10 23 23 pm" src="https://cloud.githubusercontent.com/assets/17034/19547176/a88485e8-964a-11e6-8826-195c42cfb8f8.png">

Everything compiles, but it seems we don't have package directories...as is tradition.

![image](https://cloud.githubusercontent.com/assets/17034/19547192/ccfa9f8e-964a-11e6-83e3-a24a9a0fa237.png)

**Comment by kevmoo** [comment]
symlink to what? We have to package dirs any more.

Generating package directories in web project should be just another code-gen-ish thing. Should be included when running `bazel build :game_web_ddc_bundle`

**Comment by matanlurey** [comment]
Packages was a pub-specific thing. I don't know what we'd generate, it's basically the same thing as "runfiles" has in bazel, so I imagine the right thing here is to have the iBlaze server interpret "packages/" as ".runfiles/" (or something like that)

**Comment by jakemac53** [comment]
I can take this on, we will need to add an extra argument to the server to pass in the current pub package name so we know how to route that properly but that should be relatively trivial.

**Comment by jakemac53** [comment]
Actually, we might be able to use the `${build_rule_name}.packages` file, if we fix it up to point to valid paths ;)
