### ISSUE TITLE
VM snapshot builds are not reproducible

### ISSUE THREAD

**Issue by cbracken** [dart-lang/rules_dart#59]
Ran across an interesting stack trace today:
```
#28     main (file:///private/var/tmp/_bazel_cbracken/3ae989008891a44e0350368efa332814/execroot/path/to/sdk/dartanalyzer_snapshot_helper.runfiles/path/to/sdk/pkg/analyzer_cli/bin/analyzer.dart:22)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

This indicates to me that the snapshot action is using a `ctx.file.entrypoint.path` as opposed to building with a workspace-relative path. Since my username is embedded in there, the result of this action is not reproducible across users and won't cache nicely.

**Comment by natebosch** [comment]
I think the SDK updated things to get absolute paths out of snapshots.
